[ global ]
base_path = "../../"
output_path = "Outputs/Systematic"
logging = true

[ jacobian ]
trained_surfaces = "TrainedSurfaces/OUTPUT_TRAIN_T21_suite"

[ surfaces ]
base_surface = "TrainedSurfaces/OUTPUT_TRAIN_T21_suite/TRAINOPT000.tar.gz"
trainopts = "MAGSHIFT CSP B 0.01 MAGSHIFT CSP V 0.01 MAGSHIFT CSP g 0.01 MAGSHIFT CSP i 0.01 MAGSHIFT CSP r 0.01 MAGSHIFT CSP u 0.01 WAVESHIFT CSP B 1.0 WAVESHIFT CSP V 1.0 WAVESHIFT CSP g 1.0 WAVESHIFT CSP i 1.0 WAVESHIFT CSP r 1.0 WAVESHIFT CSP u 1.0 MAGSHIFT CfA1 B 0.01 MAGSHIFT CfA1 I 0.01 MAGSHIFT CfA1 R 0.01 MAGSHIFT CfA1 U 0.01 MAGSHIFT CfA1 V 0.01 MAGSHIFT CfA2 B 0.01 MAGSHIFT CfA2 I 0.01 MAGSHIFT CfA2 R 0.01 MAGSHIFT CfA2 U 0.01 MAGSHIFT CfA2 V 0.01 MAGSHIFT CfA3_4SHOOTER2 B 0.01 MAGSHIFT CfA3_4SHOOTER2 I 0.01 MAGSHIFT CfA3_4SHOOTER2 R 0.01 MAGSHIFT CfA3_4SHOOTER2 Us 0.01 MAGSHIFT CfA3_4SHOOTER2 V 0.01 WAVESHIFT CfA3_4SHOOTER2 B 1.0 WAVESHIFT CfA3_4SHOOTER2 I 1.0 WAVESHIFT CfA3_4SHOOTER2 R 1.0 WAVESHIFT CfA3_4SHOOTER2 Us 1.0 WAVESHIFT CfA3_4SHOOTER2 V 1.0 MAGSHIFT CfA3_KEPLERCAM B 0.01 MAGSHIFT CfA3_KEPLERCAM Us 0.01 MAGSHIFT CfA3_KEPLERCAM V 0.01 MAGSHIFT CfA3_KEPLERCAM i 0.01 MAGSHIFT CfA3_KEPLERCAM r 0.01 WAVESHIFT CfA3_KEPLERCAM B 1.0 WAVESHIFT CfA3_KEPLERCAM Us 1.0 WAVESHIFT CfA3_KEPLERCAM V 1.0 WAVESHIFT CfA3_KEPLERCAM i 1.0 WAVESHIFT CfA3_KEPLERCAM r 1.0 MAGSHIFT CfA3_STANDARD B 0.01 MAGSHIFT CfA3_STANDARD I 0.01 MAGSHIFT CfA3_STANDARD R 0.01 MAGSHIFT CfA3_STANDARD U 0.01 MAGSHIFT CfA3_STANDARD V 0.01 WAVESHIFT CfA3_STANDARD B 0.01 WAVESHIFT CfA3_STANDARD I 0.01 WAVESHIFT CfA3_STANDARD R 0.01 WAVESHIFT CfA3_STANDARD U 0.01 WAVESHIFT CfA3_STANDARD V 0.01 MAGSHIFT SDSS g 0.01 MAGSHIFT SDSS i 0.01 MAGSHIFT SDSS r 0.01 MAGSHIFT SDSS u 0.01 MAGSHIFT SDSS z 0.01 WAVESHIFT SDSS g 1.0 WAVESHIFT SDSS i 1.0 WAVESHIFT SDSS r 1.0 WAVESHIFT SDSS u 1.0 WAVESHIFT SDSS z 1.0 MAGSHIFT SNLS g 0.01 MAGSHIFT SNLS i 0.01 MAGSHIFT SNLS r 0.01 MAGSHIFT SNLS z 0.01 WAVESHIFT SNLS g 1.0 WAVESHIFT SNLS i 1.0 WAVESHIFT SNLS r 1.0 WAVESHIFT SNLS z 1.0"

[ compare ]
comparison_path = "TrainedSurfaces/Systematic/OUTPUT_TRAIN"
comparison_name = "SALT2 Trained Surfaces"

[[ plot ]]
comparison_plot_path = "TrainedSurfaces/Systematic/OUTPUT_TRAIN"
phase = 0.0

[[ plot ]]
comparison_plot_path = "TrainedSurfaces/Systematic/OUTPUT_TRAIN"
phase = -15.0

[[ plot ]]
comparison_plot_path = "TrainedSurfaces/Systematic/OUTPUT_TRAIN"
phase = 45.0
