[[CFITSIO]]
arch = "aarch64"
git-tree-sha1 = "aa22dd4ce8b16e4c6b06a270e235aa46299d949c"
os = "macos"

    [[CFITSIO.download]]
    sha256 = "55a6542b45a1b2ce9caaf100cd61205c3586326ca75ec6b8cddb1f52a3d60e61"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.0.0+0/CFITSIO.v4.0.0.aarch64-apple-darwin.tar.gz"
[[CFITSIO]]
arch = "aarch64"
git-tree-sha1 = "1aff5e965da83e3fd406ae017526d09aad2db43c"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "2f8f6c66550dee0d0f8a3a80a0a598d8fb27ab7b867d1ed6ec651f1167280253"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.0.0+0/CFITSIO.v4.0.0.aarch64-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "aarch64"
git-tree-sha1 = "e8b9534a86dfaea3ca53e515da94720560390f2d"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "d9c37f42d891ab313a625666ebd47126e5af31c602d240338ef6327e56351255"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.0.0+0/CFITSIO.v4.0.0.aarch64-linux-musl.tar.gz"
[[CFITSIO]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ae2ee98a335ffe9f9181e1519c34058afbf8f73d"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "1e3c73cc06c9cb87a74ef6e3c0e4b17d66e7310e2bea4913822917356f2c3796"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.0.0+0/CFITSIO.v4.0.0.armv6l-linux-gnueabihf.tar.gz"
[[CFITSIO]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "383e2f8997b9fb7c262e06ffa3d624398287efd2"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "0e5befb29e3588621d5ecc8b75f632271f953615f0249c6a559921acd9a8fd9b"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.0.0+0/CFITSIO.v4.0.0.armv6l-linux-musleabihf.tar.gz"
[[CFITSIO]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eb42750e418e0ae8eabe79dfa333fa99650c336f"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "5db5b70caf540433efbd079ccb9f4b5c4cfc6f0806ef0773b3628c9dfc8dc0a9"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.0.0+0/CFITSIO.v4.0.0.armv7l-linux-gnueabihf.tar.gz"
[[CFITSIO]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "069442ee0f6970dd2388541d78c42b6f52b6f1e9"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "d6eb4cdf7d855bcc19c918054f795d839966b047703546aa69623c0ce91eaace"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.0.0+0/CFITSIO.v4.0.0.armv7l-linux-musleabihf.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "08eb7a7019ee29f8d3a27322afa970d94c8925a4"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "cb2ffb7184dcbbfcf8e5fe82293de75c66b8dee1aa3495786ec6715fd3f5c93b"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.0.0+0/CFITSIO.v4.0.0.i686-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "36603e2d9ea3405cbd8d1cd8654a5cd3206c0c75"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "bded958b4f01f96126820f4e6cfe9507a4c29385879a295df79c95ad35d480e1"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.0.0+0/CFITSIO.v4.0.0.i686-linux-musl.tar.gz"
[[CFITSIO]]
arch = "i686"
git-tree-sha1 = "24ce557aec9bad4e02a21881dd5b130988880b9c"
os = "windows"

    [[CFITSIO.download]]
    sha256 = "692f4aa0806b257dc841486abb428dea54a964ba235604d2f67abe7d0a5007e4"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.0.0+0/CFITSIO.v4.0.0.i686-w64-mingw32.tar.gz"
[[CFITSIO]]
arch = "powerpc64le"
git-tree-sha1 = "a15e22b40847db4afc6739c60aff49417049b557"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "4e5d0c4d37867cf3aac8a7a7ed0d3a7cc403de2fc4d7358a542847e624e3d3c3"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.0.0+0/CFITSIO.v4.0.0.powerpc64le-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "87abd1e618813b501871b2935b4e7810c24360aa"
os = "macos"

    [[CFITSIO.download]]
    sha256 = "c1dbc5b9092d580f1a5601605f6726243737304d7e14dd03c1944d418121a46b"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.0.0+0/CFITSIO.v4.0.0.x86_64-apple-darwin.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "6da2895f3ff8341c1cb0c8a3b0dfde70915677ac"
libc = "glibc"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "7dbc1097ae85bacae22552ae02c70bf4e7a2beb0cee483ea2448d672e5ffe981"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.0.0+0/CFITSIO.v4.0.0.x86_64-linux-gnu.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "388f7b758227c217de04928d833f6b00ab77c68d"
libc = "musl"
os = "linux"

    [[CFITSIO.download]]
    sha256 = "88a1b6a9240549bb753b8a2283d962aa3bb9946ef822d85f53de4028d12e57d3"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.0.0+0/CFITSIO.v4.0.0.x86_64-linux-musl.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "78575bd16d2e66310d5cfd6f77d3ae047b746dc3"
os = "freebsd"

    [[CFITSIO.download]]
    sha256 = "661bdbbf659d5cc7d3ed1123133fc221b3cd6aba0a9bc8c2964076d1b377a50e"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.0.0+0/CFITSIO.v4.0.0.x86_64-unknown-freebsd.tar.gz"
[[CFITSIO]]
arch = "x86_64"
git-tree-sha1 = "c738afd1858f94f4f3b77fbb4f0eb175f8a78569"
os = "windows"

    [[CFITSIO.download]]
    sha256 = "8c333e641c67703431373f9fcfb9bd32dca8a17f934521399d166fe141fd3e6b"
    url = "https://github.com/JuliaBinaryWrappers/CFITSIO_jll.jl/releases/download/CFITSIO-v4.0.0+0/CFITSIO.v4.0.0.x86_64-w64-mingw32.tar.gz"
