[ global ]
base_path = "../../"
output_path = "Outputs/FullRunthrough"
logging = true

[ jacobian ]
trained_surfaces = "TrainedSurfaces/OUTPUT_TRAIN_T21_suite"

[ surfaces ]
input_file = "Inputs/FullRunthrough/train_SALT2.input"
base_surface = "TrainedSurfaces/OUTPUT_TRAIN_T21_suite/TRAINOPT000.tar.gz"

[ compare ]
comparison_path = "TrainedSurfaces/OUTPUT_TRAIN_SALT2_train"
comparison_name = "SALT2 Trained Surfaces"

[ plot ]
comparison_plot_path = "TrainedSurfaces/OUTPUT_TRAIN_SALT2_train"
