[ global ]
base_path = "../../"
output_path = "Outputs/FullRunthrough"
logging = true

[ jacobian ]
trained_surfaces = "TrainedSurfaces/OUTPUT_TRAIN_T21_suite"

[ surfaces ]
trainopts = [
    "MAGSHIFT CfA3_KEPLERCAM Us 0.01",
    "WAVESHIFT CfA3_KEPLERCAM i 1.0",
    "MAGSHIFT SDSS g 0.01",
    "MAGSHIFT SDSS g,z 0.01,-0.01 MAGSHIFT CfA2 B 0.01",
    "WAVESHIFT CfA3_STANDARD r,i 10,10 MAGSHIFT CfA3_STANDARD I .01",
    "MAGSHIFT Calan/Tololo B 0.01",
    "WAVESHIFT CfA1 U 1.0"
]
base_surface = "TrainedSurfaces/OUTPUT_TRAIN_T21_suite/TRAINOPT000.tar.gz"

[ compare ]
comparison_path = "TrainedSurfaces/OUTPUT_TRAIN_SALT2_train"
comparison_name = "SALT2 Trained Surfaces"

[[ plot ]]
comparison_plot_path = "TrainedSurfaces/OUTPUT_TRAIN_SALT2_train"
