[[Expat]]
arch = "aarch64"
git-tree-sha1 = "d854bf326fc0be76e40fc9ddc2a1a2df31ab91fe"
os = "macos"

    [[Expat.download]]
    sha256 = "f93c978b5f91dafaed271c6eaaba926a505482ec68c850f64d79476ac9ab379b"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.4+0/Expat.v2.4.4.aarch64-apple-darwin.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "bfefe0b8e17bdd8a5a9b92a0d3c89bd4506b78ac"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "902d6febb0db31f8cf884a20e7f3d6aa6c97dcac2d2b9caff18293d8160c7207"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.4+0/Expat.v2.4.4.aarch64-linux-gnu.tar.gz"
[[Expat]]
arch = "aarch64"
git-tree-sha1 = "0b02a0ea7f4909a4f1deb4d243ef9653c5e534d9"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "ca5095b490da26be1a8e86bdb3e77a10700c7d1148a7b4855a46139a4618b8fe"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.4+0/Expat.v2.4.4.aarch64-linux-musl.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "efd28110929f43127ca85bb6b4fabfbda087924c"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "94463b28a8c86dc4896de2d36c4b89e008262221b1024a7b4b59770f2ce4a2f6"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.4+0/Expat.v2.4.4.armv6l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e50950b40c3b777716abaae9566f1e4aa3870fa2"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "567f5939b7008d743131f07c7a2cf9cdca04db47cc56ad9662676c363bf89dd3"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.4+0/Expat.v2.4.4.armv6l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "48dea89aa493520f835cf8389a603c02a67bded6"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "fc6e4177943bb2a475ce201ec6f3fda398e737b3c6ef39a29b095dafe290ceaa"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.4+0/Expat.v2.4.4.armv7l-linux-gnueabihf.tar.gz"
[[Expat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3cf0b45eea9677c17596b413137eeda694888745"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "e23a2b1c9086a1cf678fce77b141fa420e64d65ad5e2c1e4ded22466f96b3fde"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.4+0/Expat.v2.4.4.armv7l-linux-musleabihf.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "b1dcefc91a978a939a7bd4df9c60335cc87d70eb"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "188bf4eaaae884416d764f83147477a944a1f4a5fedbe33d489f499b5203d10d"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.4+0/Expat.v2.4.4.i686-linux-gnu.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "7decb3f6b4c650206bf0c1c1f1485eb5eb7568fa"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "ec0ab3fee183d26e74aad659e7fab3bb6d5ce85deba4b4fb259f5b12d185b426"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.4+0/Expat.v2.4.4.i686-linux-musl.tar.gz"
[[Expat]]
arch = "i686"
git-tree-sha1 = "4c1468e3b86ddc8d8651298e3d26ee54f5a16fd5"
os = "windows"

    [[Expat.download]]
    sha256 = "daa08697e1b35d4ab77e3c0d0cd0628985114ad941823faf6882bb8a98fd8c47"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.4+0/Expat.v2.4.4.i686-w64-mingw32.tar.gz"
[[Expat]]
arch = "powerpc64le"
git-tree-sha1 = "006fc81414656bd0ca01c506610d8fb6ff3b4168"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "41353773c6efc58a7be7befc1b74b7865bc395ce6ce68af14c92543c4a41ba98"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.4+0/Expat.v2.4.4.powerpc64le-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "4d9e7e380a9433090661fb448f1fd7ef5a19e285"
os = "macos"

    [[Expat.download]]
    sha256 = "62c270bdf329a5997dd0a8762ac0674ee3e63f433c31d417477c32fa7f61672a"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.4+0/Expat.v2.4.4.x86_64-apple-darwin.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "87bafe0241306176b06ea2cc2f0b9674e662a24e"
libc = "glibc"
os = "linux"

    [[Expat.download]]
    sha256 = "232718ecb06948475f4740d974b7f2708d780c020982d964a3c7733b3ffaa7ab"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.4+0/Expat.v2.4.4.x86_64-linux-gnu.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "fbd328a66f331415f66e9590360033105d4ca357"
libc = "musl"
os = "linux"

    [[Expat.download]]
    sha256 = "27ece362971ff8ac77c272eeaa4362c45de21e674e21ce4bdb1ef368b093608b"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.4+0/Expat.v2.4.4.x86_64-linux-musl.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "5fd67413c42e08a4d2ca90d36379263620054f68"
os = "freebsd"

    [[Expat.download]]
    sha256 = "b1793ff96457f0f931d44c13b977cd9f989e9e4ef9f7e2d35994ba3c815e92be"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.4+0/Expat.v2.4.4.x86_64-unknown-freebsd.tar.gz"
[[Expat]]
arch = "x86_64"
git-tree-sha1 = "6d3121e0f7aa475349989cc3947ff4f7df587afc"
os = "windows"

    [[Expat.download]]
    sha256 = "189e12f8046fac1a4f12d5ba9746a983b9881d2f6b99fb2ca4e72862e0338263"
    url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.4+0/Expat.v2.4.4.x86_64-w64-mingw32.tar.gz"
