[[isoband]]
arch = "aarch64"
git-tree-sha1 = "13fecb3016b65f528492cb08740e27719d952001"
os = "macos"

    [[isoband.download]]
    sha256 = "849bd09d7f722305ea41f175742064a15cbe4e28e039c9180f2cb3717d976491"
    url = "https://github.com/JuliaBinaryWrappers/isoband_jll.jl/releases/download/isoband-v0.2.3+0/isoband.v0.2.3.aarch64-apple-darwin.tar.gz"
[[isoband]]
arch = "aarch64"
git-tree-sha1 = "969183fe2ff4ac607e922951ba9e0a139ede910c"
libc = "glibc"
os = "linux"

    [[isoband.download]]
    sha256 = "fa9bb521671f55f9bd2645b02ac88fb91c6b57ffdc33b0c12c9bd2b5155868c7"
    url = "https://github.com/JuliaBinaryWrappers/isoband_jll.jl/releases/download/isoband-v0.2.3+0/isoband.v0.2.3.aarch64-linux-gnu.tar.gz"
[[isoband]]
arch = "aarch64"
git-tree-sha1 = "8cf3cabad0fc2ac70be1988d2e3c7122736ca990"
libc = "musl"
os = "linux"

    [[isoband.download]]
    sha256 = "0188a029e8225a185f8706b8fa2478091e7926fb3ac553632ceadb88193c1a5c"
    url = "https://github.com/JuliaBinaryWrappers/isoband_jll.jl/releases/download/isoband-v0.2.3+0/isoband.v0.2.3.aarch64-linux-musl.tar.gz"
[[isoband]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "50a0d506361d7f26cbd5811baed6155e18f8b3e5"
libc = "glibc"
os = "linux"

    [[isoband.download]]
    sha256 = "8d2e545f8a91cd02ba496ff644d169ddab21f56743265a753fef44132b373b49"
    url = "https://github.com/JuliaBinaryWrappers/isoband_jll.jl/releases/download/isoband-v0.2.3+0/isoband.v0.2.3.armv6l-linux-gnueabihf.tar.gz"
[[isoband]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "432ed489239b2b5904e6ae5491955abe6b5f1d9d"
libc = "musl"
os = "linux"

    [[isoband.download]]
    sha256 = "7b697b5d78d3b8123ede88d9c249f5c5523401c4ffdb4e531e4a33587b985302"
    url = "https://github.com/JuliaBinaryWrappers/isoband_jll.jl/releases/download/isoband-v0.2.3+0/isoband.v0.2.3.armv6l-linux-musleabihf.tar.gz"
[[isoband]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "808bafb66fa31c731d5e0b41ddf76f0b858f2d80"
libc = "glibc"
os = "linux"

    [[isoband.download]]
    sha256 = "56c2e8917221c8b6fa659774bc0f69a9a73d7d82f750c3fae95dce82638fa015"
    url = "https://github.com/JuliaBinaryWrappers/isoband_jll.jl/releases/download/isoband-v0.2.3+0/isoband.v0.2.3.armv7l-linux-gnueabihf.tar.gz"
[[isoband]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d703986de0553ce27cb5579f5a7bde078a495b0e"
libc = "musl"
os = "linux"

    [[isoband.download]]
    sha256 = "73afabe83d459e2b79c0e1168ee3c5a3a27d205969e9797b5f5ebf638fd36c20"
    url = "https://github.com/JuliaBinaryWrappers/isoband_jll.jl/releases/download/isoband-v0.2.3+0/isoband.v0.2.3.armv7l-linux-musleabihf.tar.gz"
[[isoband]]
arch = "i686"
git-tree-sha1 = "05a9248d69e6ace78b7e3496a34831c890712ecd"
libc = "glibc"
os = "linux"

    [[isoband.download]]
    sha256 = "3a182fb697591c99e2f9447c72bd3277197a40cf6e21f38a099cf9352edc2ad4"
    url = "https://github.com/JuliaBinaryWrappers/isoband_jll.jl/releases/download/isoband-v0.2.3+0/isoband.v0.2.3.i686-linux-gnu.tar.gz"
[[isoband]]
arch = "i686"
git-tree-sha1 = "556b40ca59b18d234123617f699b2ee6b475a283"
libc = "musl"
os = "linux"

    [[isoband.download]]
    sha256 = "06eedac1a2b561b0d4955498bab430423b83d9035072514ef6e7bf28832bded8"
    url = "https://github.com/JuliaBinaryWrappers/isoband_jll.jl/releases/download/isoband-v0.2.3+0/isoband.v0.2.3.i686-linux-musl.tar.gz"
[[isoband]]
arch = "i686"
git-tree-sha1 = "0f52f0c434965be44f7df94c78d33fba115c4fe7"
os = "windows"

    [[isoband.download]]
    sha256 = "6d4b654d2d098c5f74892332ed9d2cefd0ef7634e895147129ba7330ad37a526"
    url = "https://github.com/JuliaBinaryWrappers/isoband_jll.jl/releases/download/isoband-v0.2.3+0/isoband.v0.2.3.i686-w64-mingw32.tar.gz"
[[isoband]]
arch = "powerpc64le"
git-tree-sha1 = "99c269f4173fedd5a3e47eb8a25fb205c723830e"
libc = "glibc"
os = "linux"

    [[isoband.download]]
    sha256 = "0d2f370a739d149df559b5ca12fa3d12bd92e08235aba3389c6d95eefa23ecba"
    url = "https://github.com/JuliaBinaryWrappers/isoband_jll.jl/releases/download/isoband-v0.2.3+0/isoband.v0.2.3.powerpc64le-linux-gnu.tar.gz"
[[isoband]]
arch = "x86_64"
git-tree-sha1 = "afc05a0564fb7b5964b599e8d1f1598f58f8fd2f"
os = "macos"

    [[isoband.download]]
    sha256 = "ab05a60c38a661619dcf7a0df7d43b4078c37b28886ae37d08bed62339120388"
    url = "https://github.com/JuliaBinaryWrappers/isoband_jll.jl/releases/download/isoband-v0.2.3+0/isoband.v0.2.3.x86_64-apple-darwin.tar.gz"
[[isoband]]
arch = "x86_64"
git-tree-sha1 = "3a1f12ca1fd67006181b7feea7943ac231f7c966"
libc = "glibc"
os = "linux"

    [[isoband.download]]
    sha256 = "1aca580c96c6b17a22da149774fd05e79ea625fe3ec3f3e96e57d9a185eef5fc"
    url = "https://github.com/JuliaBinaryWrappers/isoband_jll.jl/releases/download/isoband-v0.2.3+0/isoband.v0.2.3.x86_64-linux-gnu.tar.gz"
[[isoband]]
arch = "x86_64"
git-tree-sha1 = "894af02cd3c9d9d319d5db3837359b7b7a926406"
libc = "musl"
os = "linux"

    [[isoband.download]]
    sha256 = "12b262cca66575f2dd6953e6cda2d76b6949fe2443ad5ed6c3c009ff4834ec94"
    url = "https://github.com/JuliaBinaryWrappers/isoband_jll.jl/releases/download/isoband-v0.2.3+0/isoband.v0.2.3.x86_64-linux-musl.tar.gz"
[[isoband]]
arch = "x86_64"
git-tree-sha1 = "83a9de7f69e0d1f4a202acf6950850756d540560"
os = "freebsd"

    [[isoband.download]]
    sha256 = "0e188a6dc71ea8bfcedd63fb00b458b8539bb2d091020b31caa15ea3503e7ca7"
    url = "https://github.com/JuliaBinaryWrappers/isoband_jll.jl/releases/download/isoband-v0.2.3+0/isoband.v0.2.3.x86_64-unknown-freebsd.tar.gz"
[[isoband]]
arch = "x86_64"
git-tree-sha1 = "8332461672c786b866c7ebba318406b38553e3a7"
os = "windows"

    [[isoband.download]]
    sha256 = "73a31a37d3db59473fe88ae3a894930347a43f23d49117f51b30fd01b6428a79"
    url = "https://github.com/JuliaBinaryWrappers/isoband_jll.jl/releases/download/isoband-v0.2.3+0/isoband.v0.2.3.x86_64-w64-mingw32.tar.gz"
